---
title: "Go to market strategy"
date: "`r Sys.Date()`"
output:
  html_notebook:
    toc: yes
    number_sections: yes
  officedown::rdocx_document:
    mapstyles:
      Normal: First Paragraph
    toc: yes
    number_sections: yes
    page_margins:
      bottom: 1
      top: 1
      right: 1.25
      left: 1.25
      header: 0.5
      footer: 0.5
      gutter: 0.5
  pdf_document:
    toc: yes
    keep_tex: yes
---

```{r setup, include=FALSE, show_col_types = FALSE}

library(officedown)
library(officer)
library(googlesheets4)

fp <- fp_par(
  text.align = "center", 
  padding.bottom = 20, padding.top = 120, 
  border.bottom = fp_border())
ft <- fp_text(shading.color='#EFEFEF', bold = TRUE)
```

\newpage

# The market

## All main battery chemistries

```{r echo=FALSE, fig.dim=c(4,2), fig.align = 'left'}
DiagrammeR::grViz("digraph {
  
  graph [layout = dot, rankdir = LR, overlap = true]
  
  all_batteries [label = 'All batteries', fontsize = 8, shape = box]
  
  node [fixedsize = true, width = 0.9, fontsize = 7, shape = oval]
  lead_acid [label = 'Lead-Acid']
  lithium [label = 'Lithium']
  
  all_batteries -> lead_acid, lithium
  
}"
  
)
```

## The market size

```{r echo=FALSE, message=FALSE, warning=FALSE, fig.dim=c(5,2)}
library(ggplot2)
library(tidyr)


all_batteries_market <- readr::read_csv(here::here("marketing", "go-to-market", "data", "all_batteries_market.csv"))
all_batteries_market <- dplyr::as_tibble(all_batteries_market)
# MAke table pivot_longer
all_batteries_market_L <- all_batteries_market %>%
  pivot_longer(
    cols = 2:6,
    names_to = "Year",
    values_to = "Market.Size"
    )

# Change the order so the lead-acid batteries go first
all_batteries_market_L <- all_batteries_market_L %>%
  dplyr::mutate(Battery.Type = factor(Battery.Type, levels = c("Lithium", "Lead-Acid")))

# Create the plot
ggplot(
  data = all_batteries_market_L
  ) +
  geom_bar(
    aes(
      x = Year, y = Market.Size, fill = Battery.Type,
      ),
    stat = "identity",
    ) +
  scale_fill_manual(values = c("green", "orange")) +
 # scale_colour_manual(values = c(Lead-Acid = "red", Lithium = "black"))
  theme_bw()

```


```{r echo=FALSE, message=FALSE, warning=FALSE, fig.align='left', tab.cap="All batteries market"}
library(kableExtra)
library(flextable)
all_batteries_market <- readr::read_csv(here::here("marketing", "go-to-market", "data", "all_batteries_market.csv"))
all_batteries_market <- dplyr::as_tibble(all_batteries_market)
flextable(all_batteries_market)
```
## Technology applicability & validation

```{r echo=FALSE, fig.dim=c(5,2)}
DiagrammeR::grViz("digraph {
  
  graph [layout = dot, rankdir = LR, overlap = true]
  
  applicability [label = 'All batteries', fontsize = 8, shape = box]
  
  node [fixedsize = true, fontsize = 7, shape = oval]
  lead_acid [label = 'Lead-Acid']
  lithium [label = 'Lithium']
  
  node [fontsize = 12, shape = none]
  yes [label = 'Yes', background = green]
  dont_know [label = '???' ]
  
  applicability -> lead_acid, lithium
  lead_acid -> yes
  lithium -> dont_know
  
}"
  
)
```




\newpage

# Lead-acid batteries

Because our technology is validated for lead-acid batteries only, we are going to focus on this market in the first stage.

Applicability for lithium batteries is a subject of future research.

## Basic classifictaion by use

```{r echo=FALSE, fig.dim=c(5,2)}
DiagrammeR::grViz("digraph {
  
  graph [layout = dot, rankdir = TD, overlap = true, fontsize = 8]
  
  all_batteries [label = 'Lead-acid \n batteries', shape = box, fontsize = 8]
  node [fixedsize = true, fontsize = 7, shape = oval]
  backup [label = 'Backup/\ntelecom']
  traction [label = 'Traction/\nforklift']
  starter [label = 'Starter']
  
  all_batteries -> backup, traction, starter
  
}"
  
)

```

```{r echo=FALSE}
lead_acid_batteries_by_type <- readr::read_csv(here::here("marketing", "go-to-market", "data", "lead_acid_batteries_by_type.csv"))
lead_acid_batteries_by_type <- dplyr::as_tibble(lead_acid_batteries_by_type)
flextable::flextable(lead_acid_batteries_by_type)
```

```{r echo=FALSE}
ggplot(
  data = lead_acid_batteries_by_type,
  aes(
    x = "", y = Market.Coverage, fill = Battery.Type
  )
) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar("y", start=0)
```
